# Regression 1 Linear Regression

다음의 항목들에 대해서 학습합니다.

* 선형회귀(Linear Regression)
* 회귀모델 평가


## 00 환경준비

### 01.Import

In [1]:
#라이브러리들을 불러오자.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

### 02.data loading

In [2]:
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/boston.csv'
data = pd.read_csv(path)

|	변수	|	설명	|
|	----	|	----	|
|	medv	|	타운별 집값(중위수)	|
|	crim	|	범죄율	|
|	zn	|	25,000 평방피트를 초과 거주지역 비율	|
|	indus	|	비소매상업지역 면적 비율	|
|	chas	|	찰스강변 위치(범주 : 강변1, 아니면 0)	|
|	nox	|	일산화질소 농도	|
|	rm	|	주택당 방 수	|
|	age	|	1940년 이전에 건축된 주택의 비율	|
|	dis	|	직업센터의 거리	|
|	rad	|	방사형 고속도로까지의 거리	|
|	tax	|	재산세율	|
|	ptratio	|	학생/교사 비율	|
|	black	|	인구 중 흑인 비율	|
|	lstat	|	인구 중 하위 계층 비율	|


## 10.데이터 이해

### 1)둘러보기

In [3]:
# 상/하위 몇개 행을 살펴 봅시다.
data.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
# 각 칼럼의 타입을 살펴 봅시다.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  black    506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


## 20.데이터 준비

### 1) 데이터 준비

In [5]:
data.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [6]:
# x, y로 나누기
target = 'medv'
x = data.drop(target, axis=1)
y = data.loc[:, target]

# train : val 나누기
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=.2, random_state = 2022)

### 2) 변수정리

### 3) NA 조치

### 4) 가변수화

### 5) Scaling

## 30.모델링1 : 단순회귀

* lstat(하위계층 비율)로만 집값(medv)을 예측하는 모델을 만들어 봅시다.

In [7]:
# 학습에 사용할 변수를 지정합니다.
features = ['lstat']

# 지정된 변수로 데이터셋을 만듭니다. 
# 학습과 검증시 아래 데이이터셋 이름을 사용합니다.
x_train1 = x_train[features]
x_val1 = x_val[features]

In [8]:
x_train1.head()

lstat
256   3.11
288   7.60
318  10.36
136  16.90
233   3.95

### 1)import

In [9]:
# 모델링용
from sklearn.linear_model import LinearRegression

# 회귀모델 평가용
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error

### 2) 모델선언

In [10]:
model1 = LinearRegression()

### 3) 모델링(학습)

In [12]:
model1.fit(x_train1, y_train)

LinearRegression()

* 회귀계수 확인하기

In [15]:
print('회귀계수 : ', model1.coef_)
print('절편 : ', model1.intercept_)
# medv = -0.9899*lstat + 35.065..

회귀계수 :  [-0.98999184]
절편 :  35.06516389947024


### 4) 검증 : 예측

In [16]:
x_val1[:5]

lstat
104  12.33
406  23.34
487  11.45
276   6.05
422  14.10

In [14]:
pred = model1.predict(x_val1) # lstat값 넣고 계산해서 나온 결과medv값 나오게 해라가 pred.에서 하는것 
pred

array([22.85856449, 11.9587543 , 23.72975731, 29.07571325, 21.10627892,
       14.92872983, 27.69962459, 18.72039859,  8.69178122, 14.13673636,
       22.08637085, 26.05623814, 24.71974915, 16.24541898, 20.83898113,
       29.78850738,  3.39532487, 15.18612771, 27.74912419, 24.6405498 ,
       17.32451009, 16.59191612,  4.74171377, 30.38250249, 31.37249433,
       27.69962459, 29.92710624, 17.18591123, 19.82918945, 30.41220224,
       25.2840445 , 28.85791505, 12.20625226, 20.11628708, 15.49302518,
       14.95842958,  0.64314755, 16.10682012, 17.45320903, 29.82810705,
       10.91926287, 18.12640348, 19.84898929,  7.95918726, 17.1166118 ,
       30.29340322, 23.68025771, 12.05775349, 15.88902192, 14.81983073,
       23.85845625, 11.70135642, 27.29372794, 27.61052533, 25.8780396 ,
       23.06646277, 25.99683863, 28.91731456, 28.01642198, 19.02729606,
       17.96800479, 15.48312526, 16.8988136 , 30.61020061, 27.74912419,
       18.1363034 , 30.6597002 , 23.14566212, 25.70974099, 18.27

### 5) 검증 : 평가

In [17]:
# MSE
mean_squared_error(  y_val  , pred   )

31.90585638589829

In [18]:
# RMSE
mean_squared_error(    y_val  , pred   , squared=False)

5.648526921764495

In [20]:
# MAE
mean_absolute_error(     y_val  , pred   )

4.201208260565667

In [19]:
# MAPE
mean_absolute_percentage_error(     y_val  , pred    )

0.227748660910789

In [21]:
# 1-MAPE = 정확도
1 - mean_absolute_percentage_error(     y_val  , pred    )

0.772251339089211

### 6) 실습

* 집값을 예측하는데, 중요한 요인으로 판단되는 feature로 모델을 만들어 봅시다.
    * model2 : feature1
    * model3 : feature2
    * model4 : feature3

In [32]:
features = ['chas']
x_train2 = x_train[features]
x_val2 = x_val[features]
model2 = LinearRegression()
model2.fit(x_train2,y_train)
pred = model2.predict(x_val2)
mean_squared_error(    y_val  , pred   , squared=False) # 8.65
mean_absolute_error(     y_val  , pred   ) # 6.82
mean_absolute_percentage_error(     y_val  , pred    ) #0.47

8.651668038180295

In [35]:
features = ['rm']
x_train3 = x_train[features]
x_val3 = x_val[features]
model3 = LinearRegression()
model3.fit(x_train3,y_train)
pred = model3.predict(x_val3)
mean_squared_error(    y_val  , pred   , squared=False) # 7.50
mean_absolute_error(     y_val  , pred   ) # 5.22
mean_absolute_percentage_error(     y_val  , pred    ) #0.3399

0.3399053171143927

In [38]:
features = ['rad']
x_train4 = x_train[features]
x_val4 = x_val[features]
model4 = LinearRegression()
model4.fit(x_train4,y_train)
pred = model4.predict(x_val4)
mean_squared_error(    y_val  , pred   , squared=False) # 7.78
mean_absolute_error(     y_val  , pred   ) # 6.13
mean_absolute_percentage_error(     y_val  , pred    ) #0.379

0.3793615087312678

## 40.모델링2 : 다중회귀

* 이번에는 다음의 변수로 예측하는 모델을 각각 만들어 봅시다.
    * model5 : lstat + ptratio 
    * model6 : lstat + ptratio + rm
    * model7 : 여러분이 원하는 조합

In [39]:
# 학습에 사용할 feature를 지정합니다.
features5 = ['lstat','ptratio' ]

x_train5 = x_train[features5]
x_val5 = x_val[features5]

In [40]:
# 학습에 사용할 변수를 지정합니다.
features6 = ['lstat','ptratio','rm' ]

x_train6 = x_train[features6]
x_val6 = x_val[features6]

In [54]:
# 학습에 사용할 변수를 지정합니다.
features7 = [   'chas', 'rm', 'rad' ,'tax'  ]

x_train7 = x_train[features7]
x_val7 = x_val[features7]

### 1)import

In [ ]:
# 이미 불러 왔으므로 여기서는 생략합니다.

### 2) 모델선언

In [55]:
model5=LinearRegression()
model6=LinearRegression()
model7=LinearRegression()

### 3) 모델링(학습)

In [56]:
model5.fit(x_train5,y_train)
model6.fit(x_train6,y_train)
model7.fit(x_train7,y_train)

LinearRegression()

* model5, 6에 대해서 회귀계수를 확인하고, 선형회귀식을 적어 봅시다.

In [57]:
# list(df) ==> df의 컬럼이름을 리스트로 보여줘
list(x_train5)
list(x_train6)
list(x_train7)

['chas', 'rm', 'rad', 'tax']

In [58]:
model5.coef_,model5.intercept_
model6.coef_,model6.intercept_
model7.coef_,model7.intercept_
# medv = 4.04*chas + 8.80*rm +2.32*rad -1.51*tax -26.91

(array([ 4.04711756e+00,  8.80095827e+00,  2.32907022e-03, -1.51062059e-02]),
 -26.918578971281903)

### 4) 검증 : 예측

In [61]:
pred5 = model5.predict(x_val5)
pred6 = model6.predict(x_val6)
pred7 = model7.predict(x_val7)
pred7

array([21.56779297, -0.50504908, 15.04624418, 37.25744233, 12.78439791,
       22.10377372, 24.23141409, 17.72969746,  9.75686826, 14.62603403,
       17.89775466, 18.77762532, 21.61070753, 15.67111222, 21.90773751,
       32.63527929,  7.08137695,  8.44552548, 24.29950375, 20.69998681,
       25.34537378, 18.65467579,  1.51917132, 33.21989934, 25.94050728,
       42.1265788 , 24.82805991, 19.80225996, 23.08828798, 27.7400702 ,
       20.94585677, 27.49784314, 19.98575684, 16.20140556, 10.15291139,
       19.43792236,  6.25408687, 22.7145508 , 18.88346199, 44.39611677,
       14.96703556, 13.3564602 , 18.24874147, 11.75468579, 17.5105125 ,
       33.14376693, 18.70791765, 21.59415714, 19.44672332, 24.51874724,
       23.34900026, 11.79869058, 31.15967364, 30.02191001, 26.29434368,
       15.16278582, 21.86892969, 23.67481354, -5.583202  , 18.8716305 ,
       18.49621983, 23.38075167, 18.6273952 , 29.48105312, 26.36251952,
       21.23598981, 29.81055073, 20.92423279, 24.24599812, 22.24

### 5) 검증 : 평가
지금까지 만든 모델 7개에 대해서 성능 비교를 해 봅시다.

In [62]:
mean_squared_error(    y_val  , pred7   , squared=False) # 7.50
mean_absolute_error(     y_val  , pred7   ) # 5.22
mean_absolute_percentage_error(     y_val  , pred7    ) #0.3399

0.2741103458481685

## 50.[추가] 결과분석
추가 단원은 여유시간이 있을 때에 진행합니다.

* 예측한 결과와 요약된 평가로 모델을 다 설명할 수는 없습니다.
* 실제값과 예측값을 비교하는 그래프를 그려봅시다.

In [ ]:
plt.scatter(y_val, pred1)

x = np.linspace(y_val.min(), y_val.max(), 10)
plt.plot(x, x, color = 'r')

plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.grid()
plt.show()

In [ ]:
plt.scatter(y_val, pred4)

x = np.linspace(y_val.min(), y_val.max(), 10)
plt.plot(x, x, color = 'r')

plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.grid()
plt.show()